# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/alireza/Documents/Compiler

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/alireza/Documents/Compiler

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alireza/Documents/Compiler/CMakeFiles /home/alireza/Documents/Compiler//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alireza/Documents/Compiler/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named BoaCompiler

# Build rule for target.
BoaCompiler: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BoaCompiler
.PHONY : BoaCompiler

# fast build rule for target.
BoaCompiler/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoaCompiler.dir/build.make CMakeFiles/BoaCompiler.dir/build
.PHONY : BoaCompiler/fast

code/Compilers.o: code/Compilers.c.o
.PHONY : code/Compilers.o

# target to build an object file
code/Compilers.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoaCompiler.dir/build.make CMakeFiles/BoaCompiler.dir/code/Compilers.c.o
.PHONY : code/Compilers.c.o

code/Compilers.i: code/Compilers.c.i
.PHONY : code/Compilers.i

# target to preprocess a source file
code/Compilers.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoaCompiler.dir/build.make CMakeFiles/BoaCompiler.dir/code/Compilers.c.i
.PHONY : code/Compilers.c.i

code/Compilers.s: code/Compilers.c.s
.PHONY : code/Compilers.s

# target to generate assembly for a file
code/Compilers.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoaCompiler.dir/build.make CMakeFiles/BoaCompiler.dir/code/Compilers.c.s
.PHONY : code/Compilers.c.s

code/MainReader.o: code/MainReader.c.o
.PHONY : code/MainReader.o

# target to build an object file
code/MainReader.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoaCompiler.dir/build.make CMakeFiles/BoaCompiler.dir/code/MainReader.c.o
.PHONY : code/MainReader.c.o

code/MainReader.i: code/MainReader.c.i
.PHONY : code/MainReader.i

# target to preprocess a source file
code/MainReader.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoaCompiler.dir/build.make CMakeFiles/BoaCompiler.dir/code/MainReader.c.i
.PHONY : code/MainReader.c.i

code/MainReader.s: code/MainReader.c.s
.PHONY : code/MainReader.s

# target to generate assembly for a file
code/MainReader.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoaCompiler.dir/build.make CMakeFiles/BoaCompiler.dir/code/MainReader.c.s
.PHONY : code/MainReader.c.s

code/Reader.o: code/Reader.c.o
.PHONY : code/Reader.o

# target to build an object file
code/Reader.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoaCompiler.dir/build.make CMakeFiles/BoaCompiler.dir/code/Reader.c.o
.PHONY : code/Reader.c.o

code/Reader.i: code/Reader.c.i
.PHONY : code/Reader.i

# target to preprocess a source file
code/Reader.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoaCompiler.dir/build.make CMakeFiles/BoaCompiler.dir/code/Reader.c.i
.PHONY : code/Reader.c.i

code/Reader.s: code/Reader.c.s
.PHONY : code/Reader.s

# target to generate assembly for a file
code/Reader.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoaCompiler.dir/build.make CMakeFiles/BoaCompiler.dir/code/Reader.c.s
.PHONY : code/Reader.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... BoaCompiler"
	@echo "... code/Compilers.o"
	@echo "... code/Compilers.i"
	@echo "... code/Compilers.s"
	@echo "... code/MainReader.o"
	@echo "... code/MainReader.i"
	@echo "... code/MainReader.s"
	@echo "... code/Reader.o"
	@echo "... code/Reader.i"
	@echo "... code/Reader.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

